using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoPopulatePlaylists.Plugins
{
    class DefaultJsonCreation
    {
        public static void CreateDefaultFile()
        {
            var filePath = Plugin.Instance.ConfigPlaylistDataPath.Value;
            if (!Directory.Exists(Path.GetDirectoryName(filePath)))
            {
                Directory.CreateDirectory(Path.GetDirectoryName(filePath));
            }
            if (!File.Exists(filePath))
            {
                // I don't know if I want to just write the text that would be the file, or create the PlaylistData objects and generate the file from that
                // I'm just going to write the text, since I'm not sure how to do comments by generating the Json from objects

                // Yeah this is kinda shit, but it gives the most control over what the example file will look like
                // Yeah I don't wanna do this again
                List<string> newLines = new List<string>()
                {
                    "{",
                    "    \"Pops\": {",
                    "        \"_\": \"All entries beginning with _ are not necessary. They are just comments.\",",
                    "        \"_1\": \"Enabled will set that playlist overrite as enabled or disabled\",",
                    "        \"Enabled\": true,",
                    "        \"_2\": \"Name will change the name of the playlist\",",
                    "        \"_3\": \"You can remove the Name line, or set it to blank to keep the default name\",",
                    "        \"Name\": \"Uncleared 1-6 Stars\",",
                    "        \"_4\": \"Difficulties can be set to Easy, Normal, Hard, Oni, and/or Ura\",",
                    "        \"_5\": \"You can also keep Difficulties empty to set it to every difficulty\",",
                    "        \"Difficulties\": [",
                    "            \"Oni\",",
                    "            \"Ura\"",
                    "        ],",
                    "        \"_6\": \"Stars can be set to 1 through 10\",",
                    "        \"_7\": \"You can also keep Stars empty to set it to every number\",",
                    "        \"Stars\": [",
                    "            1,2,3,4,5,6",
                    "        ],",
                    "        \"_8\": \"Crowns can be set to None, Silver, Gold, and/or Rainbow\",",
                    "        \"_9\": \"You can also keep Crowns empty to set it to every crown type\",",
                    "        \"Crowns\": [",
                    "            \"None\"",
                    "        ],",
                    "        \"_a\": \"Genres can be set to Pops, Anime, Vocaloid, Variety, Classical, Game Music, and/or Namco Original\",",
                    "        \"_b\": \"You can also keep Genres empty to set it to every genre\",",
                    "        \"Genres\": [",
                    "            ",
                    "        ]",
                    "    },",
                    "    \"Anime\": {",
                    "        \"Enabled\": false,",
                    "        \"Name\": \"Uncleared 4-6 Stars on Hard (Disabled)\",",
                    "        \"Difficulties\": [",
                    "            \"Hard\"",
                    "        ],",
                    "        \"Stars\": [",
                    "            4,5,6",
                    "        ],",
                    "        \"Crowns\": [",
                    "            \"None\"",
                    "        ],",
                    "        \"Genres\": [",
                    "            ",
                    "        ]",
                    "    },",
                    "    \"Vocaloid\": {",
                    "        \"Enabled\": true,",
                    "        \"Name\": \"Uncleared 4-6 Stars on Hard (Enabled)\",",
                    "        \"Difficulties\": [",
                    "            \"Hard\"",
                    "        ],",
                    "        \"Stars\": [",
                    "            4,5,6",
                    "        ],",
                    "        \"Crowns\": [",
                    "            \"None\"",
                    "        ],",
                    "        \"Genres\": [",
                    "            ",
                    "        ]",
                    "    },",
                    "    \"Variety\": {",
                    "        \"Enabled\": true,",
                    "        \"Name\": \"Uncleared Vocaloid and Variety songs\",",
                    "        \"Difficulties\": [",
                    "            ",
                    "        ],",
                    "        \"Stars\": [",
                    "            ",
                    "        ],",
                    "        \"Crowns\": [",
                    "            \"None\"",
                    "        ],",
                    "        \"Genres\": [",
                    "            \"Vocaloid\",",
                    "            \"Variety\"",
                    "        ]",
                    "    },",
                    "    \"Classical\": {",
                    "        \"Enabled\": true,",
                    "        \"Name\": \"All songs with Ura charts\",",
                    "        \"Difficulties\": [",
                    "            \"Ura\"",
                    "        ],",
                    "        \"Stars\": [",
                    "            ",
                    "        ],",
                    "        \"Crowns\": [",
                    "            ",
                    "        ],",
                    "        \"Genres\": [",
                    "            ",
                    "        ]",
                    "    },",
                    "    \"Game Music\": {",
                    "        \"Enabled\": true,",
                    "        \"Name\": \"All 8 Stars from any difficulty\",",
                    "        \"Difficulties\": [",
                    "            ",
                    "        ],",
                    "        \"Stars\": [",
                    "            8",
                    "        ],",
                    "        \"Crowns\": [",
                    "            ",
                    "        ],",
                    "        \"Genres\": [",
                    "            ",
                    "        ]",
                    "    },",
                    "    \"Namco Original\": {",
                    "        \"Enabled\": true,",
                    "        \"Name\": \"All Even Stars\",",
                    "        \"Difficulties\": [",
                    "            ",
                    "        ],",
                    "        \"Stars\": [",
                    "            2,4,6,8,10",
                    "        ],",
                    "        \"Crowns\": [",
                    "            ",
                    "        ],",
                    "        \"Genres\": [",
                    "            ",
                    "        ]",
                    "    },",
                    "    \"Playlist 1\": {",
                    "        \"Enabled\": true,",
                    "        \"Name\": \"Uncleared 1-6 Stars\",",
                    "        \"Difficulties\": [",
                    "            \"Oni\",",
                    "            \"Ura\"",
                    "        ],",
                    "        \"Stars\": [",
                    "            1,2,3,4,5,6",
                    "        ],",
                    "        \"Crowns\": [",
                    "            \"None\"",
                    "        ],",
                    "        \"Genres\": [",
                    "        ]",
                    "    },",
                    "    \"Playlist 2\": {",
                    "        \"Enabled\": true,",
                    "        \"Name\": \"Uncleared 7-8 Stars\",",
                    "        \"Difficulties\": [",
                    "            \"Oni\",",
                    "            \"Ura\"",
                    "        ],",
                    "        \"Stars\": [",
                    "            7,8",
                    "        ],",
                    "        \"Crowns\": [",
                    "            \"None\"",
                    "        ],",
                    "        \"Genres\": [",
                    "        ]",
                    "    },",
                    "    \"Playlist 3\": {",
                    "        \"Enabled\": true,",
                    "        \"Name\": \"Uncleared 9-10 Stars\",",
                    "        \"Difficulties\": [",
                    "            \"Oni\",",
                    "            \"Ura\"",
                    "        ],",
                    "        \"Stars\": [",
                    "            9,10",
                    "        ],",
                    "        \"Crowns\": [",
                    "            \"None\"",
                    "        ],",
                    "        \"Genres\": [",
                    "        ]",
                    "    },",
                    "    \"Playlist 4\": {",
                    "        \"Enabled\": true,",
                    "        \"Name\": \"All FCed Oni/Ura Songs\",",
                    "        \"Difficulties\": [",
                    "            \"Oni\",",
                    "            \"Ura\"",
                    "        ],",
                    "        \"Stars\": [",
                    "        ],",
                    "        \"Crowns\": [",
                    "            \"Gold\",",
                    "            \"Rainbow\"",
                    "        ],",
                    "        \"Genres\": [",
                    "        ]",
                    "    },",
                    "    \"Playlist 5\": {",
                    "        \"Enabled\": true,",
                    "        \"Name\": \"All DFCed Oni/Ura Songs\",",
                    "        \"Difficulties\": [",
                    "            \"Oni\",",
                    "            \"Ura\"",
                    "        ],",
                    "        \"Stars\": [",
                    "            ",
                    "        ],",
                    "        \"Crowns\": [",
                    "            \"Rainbow\"",
                    "        ],",
                    "        \"Genres\": [",
                    "        ]",
                    "    }",
                    "}",
                };

                File.WriteAllLines(Plugin.Instance.ConfigPlaylistDataPath.Value, newLines);
            }
        }
    }
}
